name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["type:bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below to help us investigate.

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which area is affected?
      options:
        - core (infrastructure, CI)
        - ingest (data ingestion service)
        - query (query service, API)
        - ui (dashboard)
        - sdk-python (Python SDK)
        - sdk-integrations (framework integrations)
        - docs (documentation)
        - other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (system unusable, data loss)
        - High (major feature broken, no workaround)
        - Medium (feature broken, workaround exists)
        - Low (minor issue, cosmetic)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Clear description of what's happening
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen instead?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Relevant environment details
      placeholder: |
        - OS: [e.g., macOS 14.0, Ubuntu 22.04]
        - MLRun version: [e.g., 0.1.0]
        - Python version: [e.g., 3.11]
        - Browser (if UI): [e.g., Chrome 120]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Error Messages
      description: Relevant log output or error messages
      render: shell

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context about the problem
